apiVersion: v1
kind: Pod
metadata:
  name: my-apache
  labels:
    name: my-apache
spec:
  containers:
  - name: my-apache
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 80


  
