apiVersion: v1
kind: Pod
metadata:
  name: my-web-app
  labels:
    name: my-web-app
spec:
  containers:
  - name: my-web-app
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    livenessProbe:
      exec:
        command:
          - cat
          - /etc/nginx/nginx.conf
      initialDelaySeconds: 1
      periodSeconds: 3
    readinessProbe:
      httpGet:
        scheme: HTTP
        path: /
        port: 80


  
