apiVersion: v1
kind: Pod
metadata:
  name: my-db-demo
  labels:
    name: myapp
spec:
  containers:
  - name: my-db-app
    image: mongo
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
      - containerPort: 27017
