apiVersion: v1
kind: Pod
metadata:
  name: mypvcapp
  labels:
    name: my-frontend-app
spec:
  containers:
  - name: frontendapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/usr/share/tomcat/html"
        name: myvolume
  volumes:
    - name: myvolume
      persistentVolumeClaim:
        claimName: mypvclaim
