apiVersion: batch/v1
kind: CronJob
metadata:
  name: mycronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hellocron
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
                - "/bin/sh"
                - -c
                - date; echo I am a CronJob
          restartPolicy: OnFailure
