apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  labels:
    run: my-nginx-service
spec:
  selector:
    app: my-nginx
  type: NodePort
  ports:
  - port: 8787
    protocol: TCP
    targetPort: 80

