apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-echo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-app-echo
    spec:
      containers:
      - name: my-app-echo
        image: gcr.io/kubernetes-e2e-test-images/echoserver-amd64:2.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
