apiVersion: v1
kind: Pod
metadata:
  name: mysecretapp
  labels:
    name: my-app
spec:
  containers:
  - name: secretapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        name: "nginx-server"
    volumeMounts:
      - mountPath: "/usr/share/mysecret"
        name: "mysecret"
  volumes:
    - name: "mysecret"
      secret:
        secretName: mysecret
