apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp-nginx-rs
spec:
  selector:
    matchLabels:
      app: myapp-nginx-rs
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp-nginx-rs
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
